baseurl = "http://gombots.github.io/"
languageCode = "en-us"
title = "Gombots"
author = "dif"
theme = "gombots"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  copyright = "gombots All rights reverved."
  analytics = ""

[permalinks]
  post = "/:year/:month/:day/:slug"
